import { Space } from '@/types/space';
import { Task } from '@/types/task';
import { CalendarEvent } from '@/types/event';
import { JournalEntry, MoodLog } from '@/types/journal';

export const INITIAL_SPACES: Space[] = [
  {
    id: 'personal',
    name: 'Personal Life',
    slug: 'personal',
    description: 'Daily habits, life admin, errands, and personal reflections',
    color: 'emerald',
    icon: 'Heart',
    taskCount: 5,
    completedTaskCount: 3,
    isFavorite: true,
  },
  {
    id: 'work',
    name: 'Work & Projects',
    slug: 'work',
    description: 'Product design, client deliverables, sprints, and strategy',
    color: 'indigo',
    icon: 'Briefcase',
    taskCount: 8,
    completedTaskCount: 4,
    isFavorite: true,
  },
  {
    id: 'study',
    name: 'Knowledge & Study',
    slug: 'study',
    description: 'Continuous learning, book notes, research papers, and courses',
    color: 'amber',
    icon: 'BookOpen',
    taskCount: 4,
    completedTaskCount: 2,
    isFavorite: true,
  },
  {
    id: 'wellness',
    name: 'Mind & Wellness',
    slug: 'wellness',
    description: 'Meditation, morning routine, fitness goals, and hydration',
    color: 'rose',
    icon: 'Sparkles',
    taskCount: 3,
    completedTaskCount: 2,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    user_id: 'guest',
    title: 'Review Bloom App Architecture & Design System',
    description: 'Ensure color tokens, glassmorphism cards, and responsive layout are consistent.',
    completed: false,
    status: 'in_progress',
    priority: 'high',
    space_id: 'work',
    due_date: new Date().toISOString().split('T')[0],
    due_time: '11:00',
    tags: ['Design', 'Next.js'],
    subtasks: [
      { id: 'sub-1', title: 'Verify dark mode contrast', completed: true },
      { id: 'sub-2', title: 'Polish glass blur cards', completed: false },
    ],
    estimated_minutes: 45,
    created_at: new Date().toISOString(),
  },
  {
    id: 'task-2',
    user_id: 'guest',
    title: 'Morning 20-minute mindful meditation & breathwork',
    description: 'Grounding session before starting the deep work sprint.',
    completed: true,
    status: 'completed',
    priority: 'medium',
    space_id: 'wellness',
    due_date: new Date().toISOString().split('T')[0],
    due_time: '08:30',
    tags: ['Mindfulness', 'Morning'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'task-3',
    user_id: 'guest',
    title: 'Prepare presentation deck for quarterly roadmap',
    description: 'Include metric targets, OKR review, and team growth plans.',
    completed: false,
    status: 'todo',
    priority: 'urgent',
    space_id: 'work',
    due_date: new Date().toISOString().split('T')[0],
    due_time: '15:00',
    tags: ['Strategy', 'Roadmap'],
    estimated_minutes: 90,
    created_at: new Date().toISOString(),
  },
  {
    id: 'task-4',
    user_id: 'guest',
    title: 'Read chapter 4 of "Atomic Habits"',
    description: 'Take notes on cue-craving-response-reward loop in the Bloom journal.',
    completed: false,
    status: 'todo',
    priority: 'low',
    space_id: 'study',
    due_date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    due_time: '20:00',
    tags: ['Reading', 'Habits'],
    estimated_minutes: 30,
    created_at: new Date().toISOString(),
  },
  {
    id: 'task-5',
    user_id: 'guest',
    title: 'Hydration goal: 2.5 Liters water with lemon',
    description: 'Keep water carafe by the desk.',
    completed: true,
    status: 'completed',
    priority: 'low',
    space_id: 'wellness',
    due_date: new Date().toISOString().split('T')[0],
    tags: ['Health'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'task-6',
    user_id: 'guest',
    title: 'Organize desktop files & clean workspace',
    description: 'Declutter physical and digital spaces for fresh clarity.',
    completed: false,
    status: 'todo',
    priority: 'medium',
    space_id: 'personal',
    due_date: new Date(Date.now() + 172800000).toISOString().split('T')[0],
    due_time: '18:00',
    tags: ['Organization'],
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_EVENTS: CalendarEvent[] = [
  {
    id: 'evt-1',
    title: 'Deep Focus: Frontend Crafting',
    description: 'No Slack, no meetings. Pure flow state building components.',
    startDate: new Date().toISOString().split('T')[0],
    startTime: '09:30',
    endTime: '12:00',
    spaceId: 'work',
    type: 'focus',
    location: 'Quiet Studio',
  },
  {
    id: 'evt-2',
    title: 'Product Design Sync',
    description: 'Review interactive prototypes and user feedback round 2.',
    startDate: new Date().toISOString().split('T')[0],
    startTime: '13:30',
    endTime: '14:30',
    spaceId: 'work',
    type: 'meeting',
    location: 'Google Meet',
  },
  {
    id: 'evt-3',
    title: 'Mindful Evening Walk & Decompression',
    description: 'Unplug and walk in the park without headphones.',
    startDate: new Date().toISOString().split('T')[0],
    startTime: '17:30',
    endTime: '18:15',
    spaceId: 'wellness',
    type: 'wellness',
    location: 'Central Park',
  },
  {
    id: 'evt-4',
    title: 'Weekly Knowledge Club: Modern UI',
    description: 'Sharing insights on fluid typography and micro-interactions.',
    startDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    startTime: '10:00',
    endTime: '11:00',
    spaceId: 'study',
    type: 'class',
    location: 'Discord Stage',
  },
];

export const INITIAL_JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: 'journal-1',
    title: 'Finding stillness amidst the busy week',
    content: 'Today I noticed how much more grounded I feel when I protect the first two hours of my morning. Starting with natural light, gentle hydration, and no notifications has drastically shifted my afternoon energy.',
    date: new Date().toISOString().split('T')[0],
    createdAt: new Date().toISOString(),
    mood: 'serene',
    promptUsed: 'What brought you a genuine sense of peace today?',
    tags: ['Mindfulness', 'Morning', 'Peace'],
    isBookmarked: true,
  },
  {
    id: 'journal-2',
    title: 'Breakthrough on component modularity',
    content: 'Finally solved the state decoupling pattern. Keeping the GlassCard layout purely visual while lifting task actions into a clean custom provider keeps things elegant and extensible.',
    date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    mood: 'radiant',
    tags: ['Coding', 'Wins', 'Design'],
  },
];

export const INITIAL_MOOD_LOGS: MoodLog[] = [
  {
    id: 'mood-1',
    date: new Date().toISOString().split('T')[0],
    time: '09:00',
    mood: 'serene',
    energyLevel: 4,
    tags: ['Rested', 'Calm', 'Grounded'],
    note: 'Slept well, smooth morning tea.',
  },
  {
    id: 'mood-2',
    date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    time: '14:00',
    mood: 'focused',
    energyLevel: 5,
    tags: ['In the zone', 'Productive'],
    note: 'Shipped two key milestones ahead of schedule.',
  },
  {
    id: 'mood-3',
    date: new Date(Date.now() - 172800000).toISOString().split('T')[0],
    time: '19:30',
    mood: 'reflective',
    energyLevel: 3,
    tags: ['Thoughtful', 'Quiet'],
    note: 'Stargazing and reading.',
  },
];

export const REFLECTIVE_PROMPTS = [
  {
    id: 'prompt-1',
    category: 'Gratitude',
    prompt: 'What is one small detail from today that made you smile or feel thankful?',
    tag: 'Gratitude',
  },
  {
    id: 'prompt-2',
    category: 'Clarity',
    prompt: 'What is currently demanding energy from you that you can consciously let go of?',
    tag: 'Clarity',
  },
  {
    id: 'prompt-3',
    category: 'Growth',
    prompt: 'What did you learn about yourself through an obstacle you encountered recently?',
    tag: 'Growth',
  },
  {
    id: 'prompt-4',
    category: 'Intention',
    prompt: 'How would you like to feel at the end of tomorrow, and what action leads there?',
    tag: 'Intention',
  },
];

export const INSPIRATIONAL_QUOTES = [
  { quote: 'Like wildflowers, you must allow yourself to grow in all the places people thought you never would.', author: 'E.V.' },
  { quote: 'Almost everything will work again if you unplug it for a few minutes, including you.', author: 'Anne Lamott' },
  { quote: 'Focus on the step in front of you, not the whole staircase.', author: 'Mindful Wisdom' },
];
